spring:
  application:
    name: server
  datasource:
    # Thêm tham số currentSchema và quan trọng nhất là gán múi giờ trực tiếp vào URL
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USERNAME:your_postgres_username}
    password: ${POSTGRES_PASSWORD:your_postgres_password}
    driver-class-name: org.postgresql.Driver
  # Cấu hình Jackson để ResponseWrapperAdvice format thời gian đúng chuẩn
  Jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_LOGIN:email_dang_nhap_brevo_cua_ban@gmail.com}
    password: ${BREVO_PASSWORD:default_brevo_password}
    sender: ${BREVO_EMAIL:email_da_dang_ky_Brevo}
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true
app:
  jwt:
    secret: ${JWT_SECRET:default_secret_key_cho_moi_truong_dev_chi_it_nhat_32_ky_tu}
    expiration: 86400000
    refresh-expiration: 604800000
  base-url: "http://localhost:8080"
  zalo-pay:
    app-id: ${ZALOPAY_APP_ID:your_zalopay_app_id}
    key1: ${ZALOPAY_KEY1:your_zalopay_key1}
    key2: ${ZALOPAY_KEY2:your_zalopay_key2}
    create-url: ${ZALOPAY_CREATE_URL:https://sandbox.zalopay.com.vn/v001/create}
    callback-url: ${ZALOPAY_CALLBACK_URL:http://localhost:8080/api/v1/zalopay/callback}
    return-url: ${ZALOPAY_RETURN_URL:http://localhost:8080/api/v1/zalopay/return}
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  use-fqn: true