spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1Uch@mch0td@!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
springdoc:
  swagger-ui:
    # Đường dẫn truy cập giao diện Swagger
    path: /swagger-ui.html
    disable-swagger-default-url: true
    # Sắp xếp các API theo thứ tự bảng chữ cái hoặc phương thức (alpha)
    operations-sorter: alpha
  api-docs:
    # Đường dẫn file JSON đặc tả API
    path: /v3/api-docs